project_name: Harmonizing Health and Machine (Farmer Minimal)
target_column: class1
id_columns: [cow_id, day]
positive_label: 1
negative_label: 0
test_size: 0.2
random_state: 42

risk_thresholds:
  urgent: 0.80
  high: 0.55
  low: 0.35

models:
  - name: logistic_regression
    type: sklearn.linear_model.LogisticRegression
    params:
      max_iter: 300
      class_weight: balanced

drop_columns:
  - iufr
  - iurr
  - iurl
  - eufr
  - iufl
  - eurl
  - eurr
  - eufl
